"""initial

Revision ID: b05b2b3d9001
Revises:
Create Date: 2025-03-14 13:21:24.939283

"""

from collections.abc import Sequence
from datetime import datetime
from typing import Union
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from werkzeug.security import generate_password_hash

# revision identifiers, used by Alembic.
revision: str = "b05b2b3d9001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "menu_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="menuitemstatus"),
            nullable=False,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ERROR", name="messagestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    conn = op.get_bind()

    # Создаем запись дефолтного админа
    admin_data = {
        "id": uuid4().hex,
        "login": "turbomanager",
        "password_hash": generate_password_hash("N>zsV,~wkgy]CaEvW_6%P@"),
        "first_name": "Default",
        "last_name": "Admin",
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    }

    # Вставляем запись
    conn.execute(
        sa.text(
            """
            INSERT INTO admins (id, login, password_hash, first_name, last_name, created_at, updated_at)
            VALUES (:id, :login, :password_hash, :first_name, :last_name, :created_at, :updated_at)
            ON CONFLICT (login) DO NOTHING
            """
        ),
        admin_data,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("messages")
    op.drop_table("menu_items")
    op.drop_table("admins")
    # ### end Alembic commands ###
