"""Phase 1: Add TelegramConnection, AIProfile, NegativeFeedback models

Revision ID: 3599bc0c0a99
Revises: 16d728e68997
Create Date: 2025-06-06 17:06:43.354074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3599bc0c0a99'
down_revision: Union[str, None] = '16d728e68997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vibe_profile_json', sa.JSON(), nullable=True, comment='Structured vibe profile data'),
    sa.Column('analysis_status', sa.Enum('PENDING', 'ANALYZING', 'COMPLETED', 'FAILED', 'OUTDATED', name='analysisstatus'), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True, comment='When the analysis was last completed'),
    sa.Column('messages_analyzed_count', sa.String(), nullable=True, comment='Number of messages used for analysis'),
    sa.Column('ai_model_used', sa.String(), nullable=True, comment="AI model used for analysis (e.g., 'gemini-pro')"),
    sa.Column('analysis_version', sa.String(), nullable=True, comment='Version of analysis algorithm'),
    sa.Column('last_error_message', sa.String(), nullable=True, comment='Last error message if analysis failed'),
    sa.Column('retry_count', sa.String(), nullable=True, comment='Number of analysis retries'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('telegram_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_string_encrypted', sa.LargeBinary(), nullable=True, comment='Encrypted Telethon session string'),
    sa.Column('last_used', sa.DateTime(), nullable=True, comment='Last time this connection was used'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this connection is currently active'),
    sa.Column('last_validation_at', sa.DateTime(), nullable=True, comment='Last time the session was validated'),
    sa.Column('validation_status', sa.String(), nullable=True, comment='Status of last validation (VALID, INVALID, EXPIRED)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('negative_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rejected_comment_text', sa.Text(), nullable=False, comment='AI-generated comment that was rejected'),
    sa.Column('original_post_content', sa.Text(), nullable=True, comment='Original post content for context'),
    sa.Column('original_post_url', sa.String(), nullable=True, comment='URL of the original post if available'),
    sa.Column('rejection_reason', sa.String(), nullable=True, comment="Optional reason for rejection (e.g., 'too_formal', 'wrong_tone')"),
    sa.Column('ai_model_used', sa.String(), nullable=True, comment='AI model that generated the rejected comment'),
    sa.Column('draft_comment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_comment_id'], ['draft_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_post_url', sa.String(), nullable=True, comment='URL of the original post'))
        batch_op.add_column(sa.Column('original_post_content', sa.Text(), nullable=True, comment='Full content of the original post'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_session_string')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_session_string', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.drop_column('original_post_content')
        batch_op.drop_column('original_post_url')

    op.drop_table('negative_feedback')
    op.drop_table('telegram_connections')
    op.drop_table('ai_profiles')
    # ### end Alembic commands ###
