"""Add pagination and safe sync fields

Revision ID: 4a6dc26a8d51
Revises: ff1692549393
Create Date: 2025-05-30 12:26:34.369790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6dc26a8d51'
down_revision: Union[str, None] = 'ff1692549393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types first
    telegrammessengerchatsyncstatus = sa.Enum('NEVER_SYNCED', 'INITIAL_MINIMAL_SYNCED', 'BACKGROUND_SYNCING', 'PARTIALLY_SYNCED', 'FULLY_SYNCED', name='telegrammessengerchatsyncstatus')
    telegrammessengerchatsyncstatus.create(op.get_bind(), checkfirst=True)
    
    userinitialsyncstatus = sa.Enum('PENDING', 'MINIMAL_COMPLETED', 'FULL_COMPLETED', 'FAILED', name='userinitialsyncstatus')
    userinitialsyncstatus.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('telegram_messenger_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialog_list_offset_date', sa.DateTime(), nullable=True, comment='Offset date for dialogs pagination'))
        batch_op.add_column(sa.Column('dialog_list_offset_id', sa.BigInteger(), nullable=True, comment='Offset ID for dialogs pagination'))
        batch_op.add_column(sa.Column('participant_list_offset', sa.Integer(), nullable=True, comment='Offset for participants pagination'))
        batch_op.add_column(sa.Column('sync_status', sa.Enum('NEVER_SYNCED', 'INITIAL_MINIMAL_SYNCED', 'BACKGROUND_SYNCING', 'PARTIALLY_SYNCED', 'FULLY_SYNCED', name='telegrammessengerchatsyncstatus'), nullable=True, comment='Current sync status for safe pagination'))
        batch_op.add_column(sa.Column('messages_pagination_cursor', sa.Text(), nullable=True, comment='JSON cursor for message pagination state'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_participants_load_limit', sa.Integer(), nullable=True, comment='Batch size for fetching participants'))
        batch_op.add_column(sa.Column('initial_sync_status', sa.Enum('PENDING', 'MINIMAL_COMPLETED', 'FULL_COMPLETED', 'FAILED', name='userinitialsyncstatus'), nullable=True, comment="Status of the user's initial safe sync process"))
        batch_op.add_column(sa.Column('last_dialog_sync_at', sa.DateTime(), nullable=True, comment='Timestamp of the last successful dialog list sync'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_dialog_sync_at')
        batch_op.drop_column('initial_sync_status')
        batch_op.drop_column('telegram_participants_load_limit')

    with op.batch_alter_table('telegram_messenger_chats', schema=None) as batch_op:
        batch_op.drop_column('messages_pagination_cursor')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('participant_list_offset')
        batch_op.drop_column('dialog_list_offset_id')
        batch_op.drop_column('dialog_list_offset_date')
        
    # Drop enum types
    sa.Enum(name='telegrammessengerchatsyncstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='userinitialsyncstatus').drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
