"""add_last_telegram_auth_at_field

Revision ID: 5931ffa0f732
Revises: 4a6dc26a8d51
Create Date: 2025-05-30 13:46:45.974851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5931ffa0f732'
down_revision: Union[str, None] = '4a6dc26a8d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_telegram_auth_at', sa.DateTime(), nullable=True, comment='Timestamp of the last successful Telegram authentication'))
        batch_op.alter_column('persona_style_description',
               existing_type=sa.TEXT(),
               comment="Describes the user's own communication style for AI, learned from their messages.",
               existing_comment="Describes the persona's communication style for AI.",
               existing_nullable=True)
        batch_op.alter_column('persona_interests_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON list of interest keywords for the user, learned from their activity.',
               existing_comment='JSON list of interest keywords for the persona.',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('persona_interests_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON list of interest keywords for the persona.',
               existing_comment='JSON list of interest keywords for the user, learned from their activity.',
               existing_nullable=True)
        batch_op.alter_column('persona_style_description',
               existing_type=sa.TEXT(),
               comment="Describes the persona's communication style for AI.",
               existing_comment="Describes the user's own communication style for AI, learned from their messages.",
               existing_nullable=True)
        batch_op.drop_column('last_telegram_auth_at')

    # ### end Alembic commands ###
