"""add_persona_fields_and_draft_comment_model

Revision ID: 66f2c8cc2158
Revises: 02065227fdc1
Create Date: 2025-05-26 13:30:12.866418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f2c8cc2158'
down_revision: Union[str, None] = '02065227fdc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=True),
    sa.Column('ai_model_used', sa.String(), nullable=True),
    sa.Column('original_post_text_preview', sa.Text(), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('final_text_to_post', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'EDITED', 'APPROVED', 'POSTED', 'FAILED_TO_POST', 'REJECTED', name='draftstatus'), nullable=False),
    sa.Column('posted_telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_message_id'], ['telegram_messenger_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_messenger_chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fetched_message_telegram_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('last_successful_fetch_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('persona_style_description', sa.Text(), nullable=True, comment="Describes the persona's communication style for AI."))
        batch_op.add_column(sa.Column('persona_interests_json', sa.JSON(), nullable=True, comment='JSON list of interest keywords for the persona.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('persona_interests_json')
        batch_op.drop_column('persona_style_description')
        batch_op.drop_column('persona_name')

    with op.batch_alter_table('telegram_messenger_chats', schema=None) as batch_op:
        batch_op.drop_column('last_successful_fetch_at')
        batch_op.drop_column('last_fetched_message_telegram_id')

    op.drop_table('draft_comments')
    # ### end Alembic commands ###
