"""add ai context summary to drafts

Revision ID: a1b2c3d4e5f6
Revises: f5a2b1c8d3e0
Create Date: 2025-07-19 15:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'f5a2b1c8d3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_context_summary', sa.Text(), nullable=True, comment="AI's summary of the post context"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.drop_column('ai_context_summary')

    # ### end Alembic commands ### 