"""Add draft comment model and persona fields

Revision ID: d8aa3a2236bd
Revises: 66f2c8cc2158
Create Date: 2025-05-26 13:40:16.073997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8aa3a2236bd'
down_revision: Union[str, None] = '66f2c8cc2158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
