"""Refactor: Drop obsolete models and consolidate structure

Revision ID: f5a2b1c8d3e0
Revises: 9240d9dd94b1
Create Date: 2025-06-12 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a2b1c8d3e0'
down_revision: Union[str, None] = '9240d9dd94b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    try:
        op.drop_constraint('telegram_messenger_chat_users_management_person_id_fkey', 'telegram_messenger_chat_users', type_='foreignkey')
    except Exception:
        pass  # Constraint might not exist
    
    # Now drop the tables
    op.drop_table('management_persons')
    op.drop_table('messages')
    op.drop_table('menu_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='menuitemstatus'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='menu_items_pkey')
    )
    op.create_table('messages',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ERROR', name='messagestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_table('management_persons',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='management_persons_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='management_persons_pkey')
    )
    # ### end Alembic commands ### 