"""add_user_digital_twin_fields

Revision ID: ff1692549393
Revises: d8aa3a2236bd
Create Date: 2025-05-26 15:44:14.658340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1692549393'
down_revision: Union[str, None] = 'd8aa3a2236bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_system_prompt', sa.Text(), nullable=True, comment="AI system prompt derived from the user's topics/interests, used for comment generation."))
        batch_op.add_column(sa.Column('last_context_analysis_at', sa.DateTime(), nullable=True, comment='Timestamp of the last successful user context analysis.'))
        batch_op.add_column(sa.Column('context_analysis_status', sa.String(), nullable=True, comment='Status of the user context analysis (e.g., PENDING, COMPLETED, FAILED).'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('context_analysis_status')
        batch_op.drop_column('last_context_analysis_at')
        batch_op.drop_column('user_system_prompt')

    # ### end Alembic commands ###
